// Code generated by goctl. DO NOT EDIT.
// Source: uav.proto

package server

import (
	"context"

	"zero-admin/rpc/uav/internal/logic/uavplanservice"
	"zero-admin/rpc/uav/internal/svc"
	"zero-admin/rpc/uav/uavlient"
)

type UavPlanServiceServer struct {
	svcCtx *svc.ServiceContext
	uavlient.UnimplementedUavPlanServiceServer
}

func NewUavPlanServiceServer(svcCtx *svc.ServiceContext) *UavPlanServiceServer {
	return &UavPlanServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *UavPlanServiceServer) UavPlanAdd(ctx context.Context, in *uavlient.AddUavPlanReq) (*uavlient.UavPlanAddResp, error) {
	l := uavplanservicelogic.NewUavPlanAddLogic(ctx, s.svcCtx)
	return l.UavPlanAdd(in)
}

func (s *UavPlanServiceServer) UavPlanList(ctx context.Context, in *uavlient.ListUavPlanReq) (*uavlient.ListUavPlanResp, error) {
	l := uavplanservicelogic.NewUavPlanListLogic(ctx, s.svcCtx)
	return l.UavPlanList(in)
}

func (s *UavPlanServiceServer) UavPlanUpdate(ctx context.Context, in *uavlient.UpdateUavPlanReq) (*uavlient.UpdateUavPlanResp, error) {
	l := uavplanservicelogic.NewUavPlanUpdateLogic(ctx, s.svcCtx)
	return l.UavPlanUpdate(in)
}

func (s *UavPlanServiceServer) UavPlanFindById(ctx context.Context, in *uavlient.UavPlanFindByIdReq) (*uavlient.ListUavPlanResp, error) {
	l := uavplanservicelogic.NewUavPlanFindByIdLogic(ctx, s.svcCtx)
	return l.UavPlanFindById(in)
}
