// Code generated by goctl. DO NOT EDIT.
// Source: uav.proto

package server

import (
	"context"

	"zero-admin/rpc/uav/internal/logic/uavhistoryservice"
	"zero-admin/rpc/uav/internal/svc"
	"zero-admin/rpc/uav/uavlient"
)

type UavHistoryServiceServer struct {
	svcCtx *svc.ServiceContext
	uavlient.UnimplementedUavHistoryServiceServer
}

func NewUavHistoryServiceServer(svcCtx *svc.ServiceContext) *UavHistoryServiceServer {
	return &UavHistoryServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *UavHistoryServiceServer) UavHistoryAdd(ctx context.Context, in *uavlient.AddUavHistoryReq) (*uavlient.UavHistoryAddResp, error) {
	l := uavhistoryservicelogic.NewUavHistoryAddLogic(ctx, s.svcCtx)
	return l.UavHistoryAdd(in)
}

func (s *UavHistoryServiceServer) UavHistoryList(ctx context.Context, in *uavlient.ListUavHistoryReq) (*uavlient.ListUavHistoryResp, error) {
	l := uavhistoryservicelogic.NewUavHistoryListLogic(ctx, s.svcCtx)
	return l.UavHistoryList(in)
}

func (s *UavHistoryServiceServer) UavHistoryUpdate(ctx context.Context, in *uavlient.UpdateUavHistoryReq) (*uavlient.UpdateUavHistoryResp, error) {
	l := uavhistoryservicelogic.NewUavHistoryUpdateLogic(ctx, s.svcCtx)
	return l.UavHistoryUpdate(in)
}

func (s *UavHistoryServiceServer) UavHistoryFindById(ctx context.Context, in *uavlient.UavHistoryFindByIdReq) (*uavlient.ListUavHistoryResp, error) {
	l := uavhistoryservicelogic.NewUavHistoryFindByIdLogic(ctx, s.svcCtx)
	return l.UavHistoryFindById(in)
}
