// Code generated by goctl. DO NOT EDIT.
// Source: uav.proto

package server

import (
	"context"

	"zero-admin/rpc/uav/internal/logic/uavmmqservice"
	"zero-admin/rpc/uav/internal/svc"
	"zero-admin/rpc/uav/uavlient"
)

type UavMMQServiceServer struct {
	svcCtx *svc.ServiceContext
	uavlient.UnimplementedUavMMQServiceServer
}

func NewUavMMQServiceServer(svcCtx *svc.ServiceContext) *UavMMQServiceServer {
	return &UavMMQServiceServer{
		svcCtx: svcCtx,
	}
}

// 获取消息列表
func (s *UavMMQServiceServer) UavMMQList(ctx context.Context, in *uavlient.UavMMQListReq) (*uavlient.UavMMQListResp, error) {
	l := uavmmqservicelogic.NewUavMMQListLogic(ctx, s.svcCtx)
	return l.UavMMQList(in)
}

// 根据设备d查询报警
func (s *UavMMQServiceServer) UavMMQConfirmById(ctx context.Context, in *uavlient.UavMMQFindByIdReq) (*uavlient.UavMMQFindByIdResp, error) {
	l := uavmmqservicelogic.NewUavMMQConfirmByIdLogic(ctx, s.svcCtx)
	return l.UavMMQConfirmById(in)
}

// 根据设备ids查询报警
func (s *UavMMQServiceServer) UavMMQFindByIds(ctx context.Context, in *uavlient.UavMMQFindByIdsReq) (*uavlient.UavMMQFindByIdsResp, error) {
	l := uavmmqservicelogic.NewUavMMQFindByIdsLogic(ctx, s.svcCtx)
	return l.UavMMQFindByIds(in)
}
