// Code generated by goctl. DO NOT EDIT.
// Source: uav.proto

package uavhistoryservice

import (
	"context"

	"zero-admin/rpc/uav/uavlient"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddUavFlyReq           = uavlient.AddUavFlyReq
	AddUavFlyResp          = uavlient.AddUavFlyResp
	AddUavHistoryReq       = uavlient.AddUavHistoryReq
	AddUavHistoryResp      = uavlient.AddUavHistoryResp
	AddUavNetworkReq       = uavlient.AddUavNetworkReq
	AddUavNetworkResp      = uavlient.AddUavNetworkResp
	AddUavPeopleReq        = uavlient.AddUavPeopleReq
	AddUavPeopleResp       = uavlient.AddUavPeopleResp
	AddUavPlanReq          = uavlient.AddUavPlanReq
	AddUavPlanResp         = uavlient.AddUavPlanResp
	DeleteUavFlyReq        = uavlient.DeleteUavFlyReq
	DeleteUavFlyResp       = uavlient.DeleteUavFlyResp
	DeleteUavHistoryReq    = uavlient.DeleteUavHistoryReq
	DeleteUavHistoryResp   = uavlient.DeleteUavHistoryResp
	DeleteUavNetworkReq    = uavlient.DeleteUavNetworkReq
	DeleteUavNetworkResp   = uavlient.DeleteUavNetworkResp
	DeleteUavPeopleReq     = uavlient.DeleteUavPeopleReq
	DeleteUavPeopleResp    = uavlient.DeleteUavPeopleResp
	DeleteUavPlanReq       = uavlient.DeleteUavPlanReq
	DeleteUavPlanResp      = uavlient.DeleteUavPlanResp
	ListUavFlyReq          = uavlient.ListUavFlyReq
	ListUavFlyResp         = uavlient.ListUavFlyResp
	ListUavHistoryReq      = uavlient.ListUavHistoryReq
	ListUavHistoryResp     = uavlient.ListUavHistoryResp
	ListUavNetworkReq      = uavlient.ListUavNetworkReq
	ListUavNetworkResp     = uavlient.ListUavNetworkResp
	ListUavPeopleReq       = uavlient.ListUavPeopleReq
	ListUavPeopleResp      = uavlient.ListUavPeopleResp
	ListUavPlanReq         = uavlient.ListUavPlanReq
	ListUavPlanResp        = uavlient.ListUavPlanResp
	ListtUavFlyData        = uavlient.ListtUavFlyData
	ListtUavHistoryData    = uavlient.ListtUavHistoryData
	ListtUavNetworkData    = uavlient.ListtUavNetworkData
	ListtUavPeopleData     = uavlient.ListtUavPeopleData
	ListtUavPlanData       = uavlient.ListtUavPlanData
	UavControlData         = uavlient.UavControlData
	UavDeviceAddReq        = uavlient.UavDeviceAddReq
	UavDeviceAddResp       = uavlient.UavDeviceAddResp
	UavDeviceFindByIdReq   = uavlient.UavDeviceFindByIdReq
	UavDeviceFindByIdResp  = uavlient.UavDeviceFindByIdResp
	UavDeviceFindByIdsReq  = uavlient.UavDeviceFindByIdsReq
	UavDeviceFindByIdsResp = uavlient.UavDeviceFindByIdsResp
	UavDeviceListData      = uavlient.UavDeviceListData
	UavDeviceListReq       = uavlient.UavDeviceListReq
	UavDeviceListResp      = uavlient.UavDeviceListResp
	UavFlyAddResp          = uavlient.UavFlyAddResp
	UavFlyData             = uavlient.UavFlyData
	UavFlyFindByIdReq      = uavlient.UavFlyFindByIdReq
	UavHistoryAddResp      = uavlient.UavHistoryAddResp
	UavHistoryFindByIdReq  = uavlient.UavHistoryFindByIdReq
	UavMMQAddReq           = uavlient.UavMMQAddReq
	UavMMQAddResp          = uavlient.UavMMQAddResp
	UavMMQFindByIdReq      = uavlient.UavMMQFindByIdReq
	UavMMQFindByIdResp     = uavlient.UavMMQFindByIdResp
	UavMMQFindByIdsReq     = uavlient.UavMMQFindByIdsReq
	UavMMQFindByIdsResp    = uavlient.UavMMQFindByIdsResp
	UavMMQListData         = uavlient.UavMMQListData
	UavMMQListReq          = uavlient.UavMMQListReq
	UavMMQListResp         = uavlient.UavMMQListResp
	UavNetworkAddResp      = uavlient.UavNetworkAddResp
	UavNetworkFindByIdReq  = uavlient.UavNetworkFindByIdReq
	UavPeopleAddResp       = uavlient.UavPeopleAddResp
	UavPeopleFindByIdReq   = uavlient.UavPeopleFindByIdReq
	UavPlanAddResp         = uavlient.UavPlanAddResp
	UavPlanFindByIdReq     = uavlient.UavPlanFindByIdReq
	UpdateUavFlyReq        = uavlient.UpdateUavFlyReq
	UpdateUavFlyResp       = uavlient.UpdateUavFlyResp
	UpdateUavHistoryReq    = uavlient.UpdateUavHistoryReq
	UpdateUavHistoryResp   = uavlient.UpdateUavHistoryResp
	UpdateUavNetworkReq    = uavlient.UpdateUavNetworkReq
	UpdateUavNetworkResp   = uavlient.UpdateUavNetworkResp
	UpdateUavPeopleReq     = uavlient.UpdateUavPeopleReq
	UpdateUavPeopleResp    = uavlient.UpdateUavPeopleResp
	UpdateUavPlanReq       = uavlient.UpdateUavPlanReq
	UpdateUavPlanResp      = uavlient.UpdateUavPlanResp

	UavHistoryService interface {
		UavHistoryAdd(ctx context.Context, in *AddUavHistoryReq, opts ...grpc.CallOption) (*UavHistoryAddResp, error)
		UavHistoryList(ctx context.Context, in *ListUavHistoryReq, opts ...grpc.CallOption) (*ListUavHistoryResp, error)
		UavHistoryUpdate(ctx context.Context, in *UpdateUavHistoryReq, opts ...grpc.CallOption) (*UpdateUavHistoryResp, error)
		UavHistoryFindById(ctx context.Context, in *UavHistoryFindByIdReq, opts ...grpc.CallOption) (*ListUavHistoryResp, error)
	}

	defaultUavHistoryService struct {
		cli zrpc.Client
	}
)

func NewUavHistoryService(cli zrpc.Client) UavHistoryService {
	return &defaultUavHistoryService{
		cli: cli,
	}
}

func (m *defaultUavHistoryService) UavHistoryAdd(ctx context.Context, in *AddUavHistoryReq, opts ...grpc.CallOption) (*UavHistoryAddResp, error) {
	client := uavlient.NewUavHistoryServiceClient(m.cli.Conn())
	return client.UavHistoryAdd(ctx, in, opts...)
}

func (m *defaultUavHistoryService) UavHistoryList(ctx context.Context, in *ListUavHistoryReq, opts ...grpc.CallOption) (*ListUavHistoryResp, error) {
	client := uavlient.NewUavHistoryServiceClient(m.cli.Conn())
	return client.UavHistoryList(ctx, in, opts...)
}

func (m *defaultUavHistoryService) UavHistoryUpdate(ctx context.Context, in *UpdateUavHistoryReq, opts ...grpc.CallOption) (*UpdateUavHistoryResp, error) {
	client := uavlient.NewUavHistoryServiceClient(m.cli.Conn())
	return client.UavHistoryUpdate(ctx, in, opts...)
}

func (m *defaultUavHistoryService) UavHistoryFindById(ctx context.Context, in *UavHistoryFindByIdReq, opts ...grpc.CallOption) (*ListUavHistoryResp, error) {
	client := uavlient.NewUavHistoryServiceClient(m.cli.Conn())
	return client.UavHistoryFindById(ctx, in, opts...)
}
