// Code generated by goctl. DO NOT EDIT.
// Source: uav.proto

package uavmmqservice

import (
	"context"

	"zero-admin/rpc/uav/uavlient"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddUavFlyReq           = uavlient.AddUavFlyReq
	AddUavFlyResp          = uavlient.AddUavFlyResp
	AddUavHistoryReq       = uavlient.AddUavHistoryReq
	AddUavHistoryResp      = uavlient.AddUavHistoryResp
	AddUavNetworkReq       = uavlient.AddUavNetworkReq
	AddUavNetworkResp      = uavlient.AddUavNetworkResp
	AddUavPeopleReq        = uavlient.AddUavPeopleReq
	AddUavPeopleResp       = uavlient.AddUavPeopleResp
	AddUavPlanReq          = uavlient.AddUavPlanReq
	AddUavPlanResp         = uavlient.AddUavPlanResp
	DeleteUavFlyReq        = uavlient.DeleteUavFlyReq
	DeleteUavFlyResp       = uavlient.DeleteUavFlyResp
	DeleteUavHistoryReq    = uavlient.DeleteUavHistoryReq
	DeleteUavHistoryResp   = uavlient.DeleteUavHistoryResp
	DeleteUavNetworkReq    = uavlient.DeleteUavNetworkReq
	DeleteUavNetworkResp   = uavlient.DeleteUavNetworkResp
	DeleteUavPeopleReq     = uavlient.DeleteUavPeopleReq
	DeleteUavPeopleResp    = uavlient.DeleteUavPeopleResp
	DeleteUavPlanReq       = uavlient.DeleteUavPlanReq
	DeleteUavPlanResp      = uavlient.DeleteUavPlanResp
	ListUavFlyReq          = uavlient.ListUavFlyReq
	ListUavFlyResp         = uavlient.ListUavFlyResp
	ListUavHistoryReq      = uavlient.ListUavHistoryReq
	ListUavHistoryResp     = uavlient.ListUavHistoryResp
	ListUavNetworkReq      = uavlient.ListUavNetworkReq
	ListUavNetworkResp     = uavlient.ListUavNetworkResp
	ListUavPeopleReq       = uavlient.ListUavPeopleReq
	ListUavPeopleResp      = uavlient.ListUavPeopleResp
	ListUavPlanReq         = uavlient.ListUavPlanReq
	ListUavPlanResp        = uavlient.ListUavPlanResp
	ListtUavFlyData        = uavlient.ListtUavFlyData
	ListtUavHistoryData    = uavlient.ListtUavHistoryData
	ListtUavNetworkData    = uavlient.ListtUavNetworkData
	ListtUavPeopleData     = uavlient.ListtUavPeopleData
	ListtUavPlanData       = uavlient.ListtUavPlanData
	UavAlertData           = uavlient.UavAlertData
	UavControlData         = uavlient.UavControlData
	UavDeviceAddReq        = uavlient.UavDeviceAddReq
	UavDeviceAddResp       = uavlient.UavDeviceAddResp
	UavDeviceFindByIdReq   = uavlient.UavDeviceFindByIdReq
	UavDeviceFindByIdResp  = uavlient.UavDeviceFindByIdResp
	UavDeviceFindByIdsReq  = uavlient.UavDeviceFindByIdsReq
	UavDeviceFindByIdsResp = uavlient.UavDeviceFindByIdsResp
	UavDeviceListData      = uavlient.UavDeviceListData
	UavDeviceListReq       = uavlient.UavDeviceListReq
	UavDeviceListResp      = uavlient.UavDeviceListResp
	UavFlyAddResp          = uavlient.UavFlyAddResp
	UavFlyData             = uavlient.UavFlyData
	UavFlyFindByIdReq      = uavlient.UavFlyFindByIdReq
	UavHistoryAddResp      = uavlient.UavHistoryAddResp
	UavHistoryFindByIdReq  = uavlient.UavHistoryFindByIdReq
	UavMMQAddReq           = uavlient.UavMMQAddReq
	UavMMQAddResp          = uavlient.UavMMQAddResp
	UavMMQFindByIdReq      = uavlient.UavMMQFindByIdReq
	UavMMQFindByIdResp     = uavlient.UavMMQFindByIdResp
	UavMMQFindByIdsReq     = uavlient.UavMMQFindByIdsReq
	UavMMQFindByIdsResp    = uavlient.UavMMQFindByIdsResp
	UavMMQListData         = uavlient.UavMMQListData
	UavMMQListReq          = uavlient.UavMMQListReq
	UavMMQListResp         = uavlient.UavMMQListResp
	UavNetworkAddResp      = uavlient.UavNetworkAddResp
	UavNetworkFindByIdReq  = uavlient.UavNetworkFindByIdReq
	UavPeopleAddResp       = uavlient.UavPeopleAddResp
	UavPeopleFindByIdReq   = uavlient.UavPeopleFindByIdReq
	UavPlanAddResp         = uavlient.UavPlanAddResp
	UavPlanFindByIdReq     = uavlient.UavPlanFindByIdReq
	Uavpoints              = uavlient.Uavpoints
	UpdateUavFlyReq        = uavlient.UpdateUavFlyReq
	UpdateUavFlyResp       = uavlient.UpdateUavFlyResp
	UpdateUavHistoryReq    = uavlient.UpdateUavHistoryReq
	UpdateUavHistoryResp   = uavlient.UpdateUavHistoryResp
	UpdateUavNetworkReq    = uavlient.UpdateUavNetworkReq
	UpdateUavNetworkResp   = uavlient.UpdateUavNetworkResp
	UpdateUavPeopleReq     = uavlient.UpdateUavPeopleReq
	UpdateUavPeopleResp    = uavlient.UpdateUavPeopleResp
	UpdateUavPlanReq       = uavlient.UpdateUavPlanReq
	UpdateUavPlanResp      = uavlient.UpdateUavPlanResp

	UavMMQService interface {
		// 获取消息列表
		UavMMQList(ctx context.Context, in *UavMMQListReq, opts ...grpc.CallOption) (*UavMMQListResp, error)
		// 根据设备d查询报警
		UavMMQConfirmById(ctx context.Context, in *UavMMQFindByIdReq, opts ...grpc.CallOption) (*UavMMQFindByIdResp, error)
		// 根据设备ids查询报警
		UavMMQFindByIds(ctx context.Context, in *UavMMQFindByIdsReq, opts ...grpc.CallOption) (*UavMMQFindByIdsResp, error)
	}

	defaultUavMMQService struct {
		cli zrpc.Client
	}
)

func NewUavMMQService(cli zrpc.Client) UavMMQService {
	return &defaultUavMMQService{
		cli: cli,
	}
}

// 获取消息列表
func (m *defaultUavMMQService) UavMMQList(ctx context.Context, in *UavMMQListReq, opts ...grpc.CallOption) (*UavMMQListResp, error) {
	client := uavlient.NewUavMMQServiceClient(m.cli.Conn())
	return client.UavMMQList(ctx, in, opts...)
}

// 根据设备d查询报警
func (m *defaultUavMMQService) UavMMQConfirmById(ctx context.Context, in *UavMMQFindByIdReq, opts ...grpc.CallOption) (*UavMMQFindByIdResp, error) {
	client := uavlient.NewUavMMQServiceClient(m.cli.Conn())
	return client.UavMMQConfirmById(ctx, in, opts...)
}

// 根据设备ids查询报警
func (m *defaultUavMMQService) UavMMQFindByIds(ctx context.Context, in *UavMMQFindByIdsReq, opts ...grpc.CallOption) (*UavMMQFindByIdsResp, error) {
	client := uavlient.NewUavMMQServiceClient(m.cli.Conn())
	return client.UavMMQFindByIds(ctx, in, opts...)
}
