// Code generated by goctl. DO NOT EDIT.
// Source: uav.proto

package uavnetworkservice

import (
	"context"

	"zero-admin/rpc/uav/uavlient"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddUavFlyReq           = uavlient.AddUavFlyReq
	AddUavFlyResp          = uavlient.AddUavFlyResp
	AddUavHistoryReq       = uavlient.AddUavHistoryReq
	AddUavHistoryResp      = uavlient.AddUavHistoryResp
	AddUavNetworkReq       = uavlient.AddUavNetworkReq
	AddUavNetworkResp      = uavlient.AddUavNetworkResp
	AddUavPeopleReq        = uavlient.AddUavPeopleReq
	AddUavPeopleResp       = uavlient.AddUavPeopleResp
	AddUavPlanReq          = uavlient.AddUavPlanReq
	AddUavPlanResp         = uavlient.AddUavPlanResp
	DeleteUavFlyReq        = uavlient.DeleteUavFlyReq
	DeleteUavFlyResp       = uavlient.DeleteUavFlyResp
	DeleteUavHistoryReq    = uavlient.DeleteUavHistoryReq
	DeleteUavHistoryResp   = uavlient.DeleteUavHistoryResp
	DeleteUavNetworkReq    = uavlient.DeleteUavNetworkReq
	DeleteUavNetworkResp   = uavlient.DeleteUavNetworkResp
	DeleteUavPeopleReq     = uavlient.DeleteUavPeopleReq
	DeleteUavPeopleResp    = uavlient.DeleteUavPeopleResp
	DeleteUavPlanReq       = uavlient.DeleteUavPlanReq
	DeleteUavPlanResp      = uavlient.DeleteUavPlanResp
	ListUavFlyReq          = uavlient.ListUavFlyReq
	ListUavFlyResp         = uavlient.ListUavFlyResp
	ListUavHistoryReq      = uavlient.ListUavHistoryReq
	ListUavHistoryResp     = uavlient.ListUavHistoryResp
	ListUavNetworkReq      = uavlient.ListUavNetworkReq
	ListUavNetworkResp     = uavlient.ListUavNetworkResp
	ListUavPeopleReq       = uavlient.ListUavPeopleReq
	ListUavPeopleResp      = uavlient.ListUavPeopleResp
	ListUavPlanReq         = uavlient.ListUavPlanReq
	ListUavPlanResp        = uavlient.ListUavPlanResp
	ListtUavFlyData        = uavlient.ListtUavFlyData
	ListtUavHistoryData    = uavlient.ListtUavHistoryData
	ListtUavNetworkData    = uavlient.ListtUavNetworkData
	ListtUavPeopleData     = uavlient.ListtUavPeopleData
	ListtUavPlanData       = uavlient.ListtUavPlanData
	UavAlertData           = uavlient.UavAlertData
	UavControlData         = uavlient.UavControlData
	UavDeviceAddReq        = uavlient.UavDeviceAddReq
	UavDeviceAddResp       = uavlient.UavDeviceAddResp
	UavDeviceFindByIdReq   = uavlient.UavDeviceFindByIdReq
	UavDeviceFindByIdResp  = uavlient.UavDeviceFindByIdResp
	UavDeviceFindByIdsReq  = uavlient.UavDeviceFindByIdsReq
	UavDeviceFindByIdsResp = uavlient.UavDeviceFindByIdsResp
	UavDeviceListData      = uavlient.UavDeviceListData
	UavDeviceListReq       = uavlient.UavDeviceListReq
	UavDeviceListResp      = uavlient.UavDeviceListResp
	UavFlyAddResp          = uavlient.UavFlyAddResp
	UavFlyData             = uavlient.UavFlyData
	UavFlyFindByIdReq      = uavlient.UavFlyFindByIdReq
	UavHistoryAddResp      = uavlient.UavHistoryAddResp
	UavHistoryFindByIdReq  = uavlient.UavHistoryFindByIdReq
	UavMMQAddReq           = uavlient.UavMMQAddReq
	UavMMQAddResp          = uavlient.UavMMQAddResp
	UavMMQFindByIdReq      = uavlient.UavMMQFindByIdReq
	UavMMQFindByIdResp     = uavlient.UavMMQFindByIdResp
	UavMMQFindByIdsReq     = uavlient.UavMMQFindByIdsReq
	UavMMQFindByIdsResp    = uavlient.UavMMQFindByIdsResp
	UavMMQListData         = uavlient.UavMMQListData
	UavMMQListReq          = uavlient.UavMMQListReq
	UavMMQListResp         = uavlient.UavMMQListResp
	UavNetworkAddResp      = uavlient.UavNetworkAddResp
	UavNetworkFindByIdReq  = uavlient.UavNetworkFindByIdReq
	UavPeopleAddResp       = uavlient.UavPeopleAddResp
	UavPeopleFindByIdReq   = uavlient.UavPeopleFindByIdReq
	UavPlanAddResp         = uavlient.UavPlanAddResp
	UavPlanFindByIdReq     = uavlient.UavPlanFindByIdReq
	UpdateUavFlyReq        = uavlient.UpdateUavFlyReq
	UpdateUavFlyResp       = uavlient.UpdateUavFlyResp
	UpdateUavHistoryReq    = uavlient.UpdateUavHistoryReq
	UpdateUavHistoryResp   = uavlient.UpdateUavHistoryResp
	UpdateUavNetworkReq    = uavlient.UpdateUavNetworkReq
	UpdateUavNetworkResp   = uavlient.UpdateUavNetworkResp
	UpdateUavPeopleReq     = uavlient.UpdateUavPeopleReq
	UpdateUavPeopleResp    = uavlient.UpdateUavPeopleResp
	UpdateUavPlanReq       = uavlient.UpdateUavPlanReq
	UpdateUavPlanResp      = uavlient.UpdateUavPlanResp

	UavNetworkService interface {
		UavNetworkAdd(ctx context.Context, in *AddUavNetworkReq, opts ...grpc.CallOption) (*UavNetworkAddResp, error)
		UavNetworkList(ctx context.Context, in *ListUavNetworkReq, opts ...grpc.CallOption) (*ListUavNetworkResp, error)
		UavNetworkUpdate(ctx context.Context, in *UpdateUavNetworkReq, opts ...grpc.CallOption) (*UpdateUavNetworkResp, error)
		UavNetworkFindById(ctx context.Context, in *UavNetworkFindByIdReq, opts ...grpc.CallOption) (*ListUavNetworkResp, error)
	}

	defaultUavNetworkService struct {
		cli zrpc.Client
	}
)

func NewUavNetworkService(cli zrpc.Client) UavNetworkService {
	return &defaultUavNetworkService{
		cli: cli,
	}
}

func (m *defaultUavNetworkService) UavNetworkAdd(ctx context.Context, in *AddUavNetworkReq, opts ...grpc.CallOption) (*UavNetworkAddResp, error) {
	client := uavlient.NewUavNetworkServiceClient(m.cli.Conn())
	return client.UavNetworkAdd(ctx, in, opts...)
}

func (m *defaultUavNetworkService) UavNetworkList(ctx context.Context, in *ListUavNetworkReq, opts ...grpc.CallOption) (*ListUavNetworkResp, error) {
	client := uavlient.NewUavNetworkServiceClient(m.cli.Conn())
	return client.UavNetworkList(ctx, in, opts...)
}

func (m *defaultUavNetworkService) UavNetworkUpdate(ctx context.Context, in *UpdateUavNetworkReq, opts ...grpc.CallOption) (*UpdateUavNetworkResp, error) {
	client := uavlient.NewUavNetworkServiceClient(m.cli.Conn())
	return client.UavNetworkUpdate(ctx, in, opts...)
}

func (m *defaultUavNetworkService) UavNetworkFindById(ctx context.Context, in *UavNetworkFindByIdReq, opts ...grpc.CallOption) (*ListUavNetworkResp, error) {
	client := uavlient.NewUavNetworkServiceClient(m.cli.Conn())
	return client.UavNetworkFindById(ctx, in, opts...)
}
