// Code generated by goctl. DO NOT EDIT.
// Source: uav.proto

package uavflyservice

import (
	"context"

	"zero-admin/rpc/uav/uavlient"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddUavFlyReq           = uavlient.AddUavFlyReq
	AddUavFlyResp          = uavlient.AddUavFlyResp
	AddUavHistoryReq       = uavlient.AddUavHistoryReq
	AddUavHistoryResp      = uavlient.AddUavHistoryResp
	AddUavNetworkReq       = uavlient.AddUavNetworkReq
	AddUavNetworkResp      = uavlient.AddUavNetworkResp
	AddUavPeopleReq        = uavlient.AddUavPeopleReq
	AddUavPeopleResp       = uavlient.AddUavPeopleResp
	AddUavPlanReq          = uavlient.AddUavPlanReq
	AddUavPlanResp         = uavlient.AddUavPlanResp
	DeleteUavFlyReq        = uavlient.DeleteUavFlyReq
	DeleteUavFlyResp       = uavlient.DeleteUavFlyResp
	DeleteUavHistoryReq    = uavlient.DeleteUavHistoryReq
	DeleteUavHistoryResp   = uavlient.DeleteUavHistoryResp
	DeleteUavNetworkReq    = uavlient.DeleteUavNetworkReq
	DeleteUavNetworkResp   = uavlient.DeleteUavNetworkResp
	DeleteUavPeopleReq     = uavlient.DeleteUavPeopleReq
	DeleteUavPeopleResp    = uavlient.DeleteUavPeopleResp
	DeleteUavPlanReq       = uavlient.DeleteUavPlanReq
	DeleteUavPlanResp      = uavlient.DeleteUavPlanResp
	ListUavFlyReq          = uavlient.ListUavFlyReq
	ListUavFlyResp         = uavlient.ListUavFlyResp
	ListUavHistoryReq      = uavlient.ListUavHistoryReq
	ListUavHistoryResp     = uavlient.ListUavHistoryResp
	ListUavNetworkReq      = uavlient.ListUavNetworkReq
	ListUavNetworkResp     = uavlient.ListUavNetworkResp
	ListUavPeopleReq       = uavlient.ListUavPeopleReq
	ListUavPeopleResp      = uavlient.ListUavPeopleResp
	ListUavPlanReq         = uavlient.ListUavPlanReq
	ListUavPlanResp        = uavlient.ListUavPlanResp
	ListtUavFlyData        = uavlient.ListtUavFlyData
	ListtUavHistoryData    = uavlient.ListtUavHistoryData
	ListtUavNetworkData    = uavlient.ListtUavNetworkData
	ListtUavPeopleData     = uavlient.ListtUavPeopleData
	ListtUavPlanData       = uavlient.ListtUavPlanData
	UavAlertData           = uavlient.UavAlertData
	UavControlData         = uavlient.UavControlData
	UavDeviceAddReq        = uavlient.UavDeviceAddReq
	UavDeviceAddResp       = uavlient.UavDeviceAddResp
	UavDeviceFindByIdReq   = uavlient.UavDeviceFindByIdReq
	UavDeviceFindByIdResp  = uavlient.UavDeviceFindByIdResp
	UavDeviceFindByIdsReq  = uavlient.UavDeviceFindByIdsReq
	UavDeviceFindByIdsResp = uavlient.UavDeviceFindByIdsResp
	UavDeviceListData      = uavlient.UavDeviceListData
	UavDeviceListReq       = uavlient.UavDeviceListReq
	UavDeviceListResp      = uavlient.UavDeviceListResp
	UavFlyAddResp          = uavlient.UavFlyAddResp
	UavFlyData             = uavlient.UavFlyData
	UavFlyFindByIdReq      = uavlient.UavFlyFindByIdReq
	UavHistoryAddResp      = uavlient.UavHistoryAddResp
	UavHistoryFindByIdReq  = uavlient.UavHistoryFindByIdReq
	UavMMQAddReq           = uavlient.UavMMQAddReq
	UavMMQAddResp          = uavlient.UavMMQAddResp
	UavMMQFindByIdReq      = uavlient.UavMMQFindByIdReq
	UavMMQFindByIdResp     = uavlient.UavMMQFindByIdResp
	UavMMQFindByIdsReq     = uavlient.UavMMQFindByIdsReq
	UavMMQFindByIdsResp    = uavlient.UavMMQFindByIdsResp
	UavMMQListData         = uavlient.UavMMQListData
	UavMMQListReq          = uavlient.UavMMQListReq
	UavMMQListResp         = uavlient.UavMMQListResp
	UavNetworkAddResp      = uavlient.UavNetworkAddResp
	UavNetworkFindByIdReq  = uavlient.UavNetworkFindByIdReq
	UavPeopleAddResp       = uavlient.UavPeopleAddResp
	UavPeopleFindByIdReq   = uavlient.UavPeopleFindByIdReq
	UavPlanAddResp         = uavlient.UavPlanAddResp
	UavPlanFindByIdReq     = uavlient.UavPlanFindByIdReq
	UpdateUavFlyReq        = uavlient.UpdateUavFlyReq
	UpdateUavFlyResp       = uavlient.UpdateUavFlyResp
	UpdateUavHistoryReq    = uavlient.UpdateUavHistoryReq
	UpdateUavHistoryResp   = uavlient.UpdateUavHistoryResp
	UpdateUavNetworkReq    = uavlient.UpdateUavNetworkReq
	UpdateUavNetworkResp   = uavlient.UpdateUavNetworkResp
	UpdateUavPeopleReq     = uavlient.UpdateUavPeopleReq
	UpdateUavPeopleResp    = uavlient.UpdateUavPeopleResp
	UpdateUavPlanReq       = uavlient.UpdateUavPlanReq
	UpdateUavPlanResp      = uavlient.UpdateUavPlanResp

	UavFlyService interface {
		// 添加设备
		UavFlyAdd(ctx context.Context, in *AddUavFlyReq, opts ...grpc.CallOption) (*UavFlyAddResp, error)
		// 获取设备列表
		UavFlyList(ctx context.Context, in *ListUavFlyReq, opts ...grpc.CallOption) (*ListUavFlyResp, error)
		// 修改设备表
		UavFlyUpdate(ctx context.Context, in *UpdateUavFlyReq, opts ...grpc.CallOption) (*UpdateUavFlyResp, error)
		// 根据设备d查询报警
		UavFlyFindById(ctx context.Context, in *UavFlyFindByIdReq, opts ...grpc.CallOption) (*ListUavFlyResp, error)
	}

	defaultUavFlyService struct {
		cli zrpc.Client
	}
)

func NewUavFlyService(cli zrpc.Client) UavFlyService {
	return &defaultUavFlyService{
		cli: cli,
	}
}

// 添加设备
func (m *defaultUavFlyService) UavFlyAdd(ctx context.Context, in *AddUavFlyReq, opts ...grpc.CallOption) (*UavFlyAddResp, error) {
	client := uavlient.NewUavFlyServiceClient(m.cli.Conn())
	return client.UavFlyAdd(ctx, in, opts...)
}

// 获取设备列表
func (m *defaultUavFlyService) UavFlyList(ctx context.Context, in *ListUavFlyReq, opts ...grpc.CallOption) (*ListUavFlyResp, error) {
	client := uavlient.NewUavFlyServiceClient(m.cli.Conn())
	return client.UavFlyList(ctx, in, opts...)
}

// 修改设备表
func (m *defaultUavFlyService) UavFlyUpdate(ctx context.Context, in *UpdateUavFlyReq, opts ...grpc.CallOption) (*UpdateUavFlyResp, error) {
	client := uavlient.NewUavFlyServiceClient(m.cli.Conn())
	return client.UavFlyUpdate(ctx, in, opts...)
}

// 根据设备d查询报警
func (m *defaultUavFlyService) UavFlyFindById(ctx context.Context, in *UavFlyFindByIdReq, opts ...grpc.CallOption) (*ListUavFlyResp, error) {
	client := uavlient.NewUavFlyServiceClient(m.cli.Conn())
	return client.UavFlyFindById(ctx, in, opts...)
}
