// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	UserName string `json:"userName"`
	Password string `json:"password"`
}

type LoginResp struct {
	Code             string `json:"code"`
	Message          string `json:"message"`
	Status           string `json:"status"`
	CurrentAuthority string `json:"currentAuthority"`
	Id               int64  `json:"id"`
	UserName         string `json:"userName"`
	AccessToken      string `json:"token"`
	AccessExpire     int64  `json:"accessExpire"`
	RefreshAfter     int64  `json:"refreshAfter"`
}

type ListMenuTree struct {
	Id       int64  `json:"id"`       // 编号
	Path     string `json:"path"`     // 菜单路径
	Name     string `json:"name"`     // 菜单名称
	ParentId int64  `json:"parentId"` // 父菜单ID，一级菜单为0
	Icon     string `json:"icon"`     // 菜单图标
}

type ListMenuTreeVue struct {
	Id           int64        `json:"id"`
	ParentId     int64        `json:"parentId"`
	Title        string       `json:"title"`
	Path         string       `json:"path"`
	Name         string       `json:"name"`
	Icon         string       `json:"icon"`
	VueRedirect  string       `json:"redirect"`
	VueComponent string       `json:"component"`
	Meta         MenuTreeMeta `json:"meta"`
}

type MenuTreeMeta struct {
	Title string `json:"title"`
	Icon  string `json:"icon"`
}

type UserInfoResp struct {
	Code        string             `json:"code"`
	Message     string             `json:"message"`
	Avatar      string             `json:"avatar"`
	Name        string             `json:"name"`
	MenuTree    []*ListMenuTree    `json:"menuTree"`
	MenuTreeVue []*ListMenuTreeVue `json:"menuTreeVue"`
}

type AddUserReq struct {
	Email    string `json:"email"`
	Mobile   string `json:"mobile"`
	Name     string `json:"name"`
	NickName string `json:"nickName"`
	DeptId   int64  `json:"deptId"`
	RoleId   int64  `json:"roleId"`
	JobId    int64  `json:"jobId"`
	Status   int64  `json:"status"` // 状态  0：禁用   1：正常
}

type AddUserResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type ListUserReq struct {
	Current  int64  `json:"current,default=1"`
	PageSize int64  `json:"pageSize,default=20"`
	Name     string `json:"name,optional"`
	NickName string `json:"nickName,optional"`
	Mobile   string `json:"mobile,optional"`
	Email    string `json:"email,optional"`
	Status   int64  `json:"status,optional,default=2"`
	DeptId   int64  `json:"deptId,optional"`
	JobId    int64  `json:"deptId,optional"`
}

type ListUserData struct {
	Id             int64  `json:"id"`             // 编号
	Name           string `json:"name"`           // 用户名
	NickName       string `json:"nickName"`       // 昵称
	Avatar         string `json:"avatar"`         // 头像
	Email          string `json:"email"`          // 邮箱
	Mobile         string `json:"mobile"`         // 手机号
	Status         int64  `json:"status"`         // 状态  0：禁用   1：正常
	DeptId         int64  `json:"deptId"`         // 机构ID
	CreateBy       string `json:"createBy"`       // 创建人
	CreateTime     string `json:"createTime"`     // 创建时间
	LastUpdateBy   string `json:"lastUpdateBy"`   // 更新人
	LastUpdateTime string `json:"lastUpdateTime"` // 更新时间
	DelFlag        int64  `json:"delFlag"`        // 是否删除  0：已删除  1：正常
	JobId          int64  `json:"jobId"`
	RoleId         int64  `json:"roleId"`
	RoleName       string `json:"roleName"`
	JobName        string `json:"jobName"`
	DeptName       string `json:"deptName"`
}

type ListUserResp struct {
	Code     string          `json:"code"`
	Message  string          `json:"message"`
	Current  int64           `json:"current,default=1"`
	Data     []*ListUserData `json:"data"`
	PageSize int64           `json:"pageSize,default=20"`
	Success  bool            `json:"success"`
	Total    int64           `json:"total"`
}

type UpdateUserReq struct {
	Id       int64  `json:"id"`
	Email    string `json:"email"`
	Mobile   string `json:"mobile"`
	Name     string `json:"name"`
	NickName string `json:"nickName"`
	DeptId   int64  `json:"deptId"`
	RoleId   int64  `json:"roleId"`
	Status   int64  `json:"status"`
	JobId    int64  `json:"jobId"`
	DelFlag  int64  `json:"delFlag,default=2"` // 是否删除  0：已删除  1：正常
}

type UpdateUserResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type DeleteUserReq struct {
	Ids []int64 `json:"ids"`
}

type DeleteUserResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type ReSetPasswordReq struct {
	Id int64 `json:"id"`
}

type ReSetPasswordResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type UserStatusReq struct {
	Id     int64 `json:"id"`
	Status int64 `json:"status"` // 状态  0：禁用   1：正常
}

type UserStatusResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type RoleAllResp struct {
	Id     int64  `json:"id"`
	Name   string `json:"name"`
	Remark string `json:"remark"`
}

type DeptAllResp struct {
	Id       int64  `json:"id"`
	Value    string `json:"value"`
	Title    string `json:"title"`
	ParentId int64  `json:"parentId"`
}

type JobAllResp struct {
	Id      int64  `json:"id"`
	JobName string `json:"jobName"`
}

type SelectDataReq struct {
	Current  int64 `json:"current,default=1"`
	PageSize int64 `json:"pageSize,default=20"`
}

type SelectDataResp struct {
	Code    string         `json:"code"`
	Message string         `json:"message"`
	RoleAll []*RoleAllResp `json:"roleAll"`
	DeptAll []*DeptAllResp `json:"deptAll"`
	JobAll  []*JobAllResp  `json:"jobAll"`
}

type AddRoleReq struct {
	Name   string `json:"name"`            // 角色名称
	Remark string `json:"remark,optional"` // 备注
	Status int64  `json:"status"`          // 状态
}

type AddRoleResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type ListRoleReq struct {
	Current  int64  `json:"current,default=1"`
	PageSize int64  `json:"pageSize,default=20"`
	Name     string `json:"name,optional "`
	Status   int64  `json:"status,default=2"`
}

type ListRoleData struct {
	Id             int64  `json:"id"`             // 编号
	Name           string `json:"name"`           // 角色名称
	Remark         string `json:"remark"`         // 备注
	CreateBy       string `json:"createBy"`       // 创建人
	CreateTime     string `json:"createTime"`     // 创建时间
	LastUpdateBy   string `json:"lastUpdateBy"`   // 更新人
	LastUpdateTime string `json:"lastUpdateTime"` // 更新时间
	DelFlag        int64  `json:"delFlag"`        // 是否删除  0：已删除  1：正常
	Label          string `json:"label"`          // 编号
	Value          string `json:"value"`          // 角色名称
	Status         int64  `json:"status"`         // 状态
}

type ListRoleResp struct {
	Code     string          `json:"code"`
	Message  string          `json:"message"`
	Current  int64           `json:"current,default=1"`
	Data     []*ListRoleData `json:"data"`
	PageSize int64           `json:"pageSize,default=20"`
	Success  bool            `json:"success"`
	Total    int64           `json:"total"`
}

type UpdateRoleReq struct {
	Id     int64  `json:"id"`     // 编号
	Name   string `json:"name"`   // 角色名称
	Remark string `json:"remark"` // 备注
	Status int64  `json:"status"` // 状态
}

type UpdateRoleResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type DeleteRoleReq struct {
	Ids []int64 `json:"ids"`
}

type DeleteRoleResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type RoleMenuIdsReq struct {
}

type RoleMenuIdsResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type UpdateRoleMenuReq struct {
	RoleId  int64   `json:"roleId"`
	MenuIds []int64 `json:"menuIds"`
}

type UpdateRoleMenuResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type ListMenuData struct {
	Key      string `json:"key"`      // 菜单名称
	Title    string `json:"title"`    // 菜单名称
	ParentId int64  `json:"parentId"` // 父菜单ID，一级菜单为0
	Id       int64  `json:"id"`       // 父菜单ID，一级菜单为0
	Label    string `json:"label"`    // 父菜单ID，一级菜单为0
}

type RoleMenuReq struct {
	Id int64 `json:"id,optional"`
}

type RoleMenuResp struct {
	AllData  []*ListMenuData `json:"allData"`
	RoleData []int64         `json:"userData"`
	Code     string          `json:"code"`
	Message  string          `json:"message"`
}

type AddMenuReq struct {
	Name          string `json:"name"`                   // 菜单名称
	ParentId      int64  `json:"parentId,optional"`      // 父菜单ID，一级菜单为0
	Url           string `json:"url,optional"`           // 菜单URL,类型：1.普通页面（如用户管理， /sysmodel/user） 2.嵌套完整外部页面，以http(s)开头的链接 3.嵌套服务器页面，使用iframe:前缀+目标URL(如SQL监控， iframe:/druid/login.html, iframe:前缀会替换成服务器地址)
	Perms         string `json:"perms,optional"`         // 授权(多个用逗号分隔，如：sysmodel:user:add,sysmodel:user:edit)
	Type          int64  `json:"type,optional"`          // 类型   0：目录   1：菜单   2：按钮
	Icon          string `json:"icon,optional"`          // 菜单图标
	OrderNum      int64  `json:"orderNum,optional"`      // 排序
	VuePath       string `json:"vuePath,optional"`       // vue系统的path
	VueComponent  string `json:"vueComponent,optional"`  // vue的页面
	VueIcon       string `json:"vueIcon,optional"`       // vue的图标
	VueRedirect   string `json:"vueRedirect,optional"`   // vue的路由重定向
	DelFlag       int64  `json:"delFlag"`                // 是否删除  0：已删除  1：正常
	BackgroundUrl string `json:"backgroundUrl,optional"` // 后台地址
}

type AddMenuResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type ListMenuReq struct {
	Name string `json:"name,optional"`
	Url  string `json:"url,optional "`
}

type ListtMenuData struct {
	Id             int64  `json:"id"`             // 编号
	Key            string `json:"key"`            // 菜单名称
	Name           string `json:"name"`           // 菜单名称
	Title          string `json:"title"`          // 菜单名称
	ParentId       int64  `json:"parentId"`       // 父菜单ID，一级菜单为0
	Url            string `json:"url"`            // 菜单URL,类型：1.普通页面（如用户管理， /sysmodel/user） 2.嵌套完整外部页面，以http(s)开头的链接 3.嵌套服务器页面，使用iframe:前缀+目标URL(如SQL监控， iframe:/druid/login.html, iframe:前缀会替换成服务器地址)
	Perms          string `json:"perms"`          // 授权(多个用逗号分隔，如：sysmodel:user:add,sysmodel:user:edit)
	Type           int64  `json:"type"`           // 类型   0：目录   1：菜单   2：按钮
	Icon           string `json:"icon"`           // 菜单图标
	OrderNum       int64  `json:"orderNum"`       // 排序
	CreateBy       string `json:"createBy"`       // 创建人
	CreateTime     string `json:"createTime"`     // 创建时间
	LastUpdateBy   string `json:"lastUpdateBy"`   // 更新人
	LastUpdateTime string `json:"lastUpdateTime"` // 更新时间
	DelFlag        int64  `json:"delFlag"`        // 是否删除  0：已删除  1：正常
	VuePath        string `json:"vuePath"`        // vue系统的path
	VueComponent   string `json:"vueComponent"`   // vue的页面
	VueIcon        string `json:"vueIcon"`        // vue的图标
	VueRedirect    string `json:"vueRedirect"`    // vue的路由重定向
	BackgroundUrl  string `json:"backgroundUrl"`  // 后台地址
}

type ListMenuResp struct {
	Code    string           `json:"code"`
	Message string           `json:"message"`
	Data    []*ListtMenuData `json:"data"`
	Success bool             `json:"success"`
	Total   int64            `json:"total"`
}

type UpdateMenuReq struct {
	Id            int64  `json:"id"`                     // 编号
	Name          string `json:"name"`                   // 菜单名称
	ParentId      int64  `json:"parentId"`               // 父菜单ID，一级菜单为0
	Url           string `json:"url,optional"`           // 菜单URL,类型：1.普通页面（如用户管理， /sysmodel/user） 2.嵌套完整外部页面，以http(s)开头的链接 3.嵌套服务器页面，使用iframe:前缀+目标URL(如SQL监控， iframe:/druid/login.html, iframe:前缀会替换成服务器地址)
	Perms         string `json:"perms,optional"`         // 授权(多个用逗号分隔，如：sysmodel:user:add,sysmodel:user:edit)
	Type          int64  `json:"type,optional"`          // 类型   0：目录   1：菜单   2：按钮
	Icon          string `json:"icon,optional"`          // 菜单图标
	OrderNum      int64  `json:"orderNum,optional"`      // 排序
	VuePath       string `json:"vuePath,optional"`       // vue系统的path
	VueComponent  string `json:"vueComponent,optional"`  // vue的页面
	VueIcon       string `json:"vueIcon,optional"`       // vue的图标
	VueRedirect   string `json:"vueRedirect,optional"`   // vue的路由重定向
	DelFlag       int64  `json:"delFlag"`                // 是否删除  0：已删除  1：正常
	BackgroundUrl string `json:"backgroundUrl,optional"` // 后台地址
}

type UpdateMenuResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type DeleteMenuReq struct {
	Ids []int64 `json:"ids"`
}

type DeleteMenuResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type AddDictReq struct {
	Value       string `json:"value"`                // 数据值
	Label       string `json:"label"`                // 标签名
	Type        string `json:"type"`                 // 类型
	Description string `json:"description,optional"` // 描述
	Sort        int64  `json:"sort"`                 // 排序（升序）
	Remarks     string `json:"remarks,optional"`     // 备注信息
	DelFlag     int64  `json:"delFlag"`              // 是否删除  0：已删除  1：正常
}

type AddDictResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type ListDictReq struct {
	Current  int64  `json:"current,default=1"`
	PageSize int64  `json:"pageSize,default=20"`
	Value    string `json:"value,optional"`
	Label    string `json:"label,optional"`
	DelFlag  int64  `json:"delFlag,default=2"`
	Type     string `json:"type,optional "`
}

type ListDictData struct {
	Id             int64   `json:"id"`             // 编号
	Value          string  `json:"value"`          // 数据值
	Label          string  `json:"label"`          // 标签名
	Type           string  `json:"type"`           // 类型
	Description    string  `json:"description"`    // 描述
	Sort           float64 `json:"sort"`           // 排序（升序）
	CreateBy       string  `json:"createBy"`       // 创建人
	CreateTime     string  `json:"createTime"`     // 创建时间
	LastUpdateBy   string  `json:"lastUpdateBy"`   // 更新人
	LastUpdateTime string  `json:"lastUpdateTime"` // 更新时间
	Remarks        string  `json:"remarks"`        // 备注信息
	DelFlag        int64   `json:"delFlag"`        // 是否删除  0：已删除  1：正常
}

type ListDictResp struct {
	Code     string          `json:"code"`
	Message  string          `json:"message"`
	Current  int64           `json:"current,default=1"`
	Data     []*ListDictData `json:"data"`
	PageSize int64           `json:"pageSize,default=20"`
	Success  bool            `json:"success"`
	Total    int64           `json:"total"`
}

type UpdateDictReq struct {
	Id          int64  `json:"id"`          // 编号
	Value       string `json:"value"`       // 数据值
	Label       string `json:"label"`       // 标签名
	Type        string `json:"type"`        // 类型
	Description string `json:"description"` // 描述
	Sort        int64  `json:"sort"`        // 排序（升序）
	Remarks     string `json:"remarks"`     // 备注信息
	DelFlag     int64  `json:"delFlag"`     // 是否删除  0：已删除  1：正常
}

type UpdateDictResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type DeleteDictReq struct {
	Ids []int64 `json:"ids"`
}

type DeleteDictResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type AddDeptReq struct {
	Name      string  `json:"name"`              // 机构名称
	ParentId  int64   `json:"parentId"`          // 上级机构ID，一级机构为0
	ParentIds []int64 `json:"parentIds"`         // 上级机构IDs
	OrderNum  int64   `json:"orderNum"`          // 排序
	DelFlag   int64   `json:"delFlag,default=2"` // 是否删除  0：已删除  1：正常
}

type AddDeptResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type ListDeptReq struct {
	Name     string `json:"name,optional"`
	CreateBy string `json:"createBy,optional"`
}

type ListDeptData struct {
	Id             int64   `json:"id"`             // 编号
	Name           string  `json:"name"`           // 机构名称
	ParentId       int64   `json:"parentId"`       // 上级机构ID，一级机构为0
	ParentIds      []int64 `json:"parentIds"`      // 上级机构ID
	OrderNum       int64   `json:"orderNum"`       // 排序
	CreateBy       string  `json:"createBy"`       // 创建人
	CreateTime     string  `json:"createTime"`     // 创建时间
	LastUpdateBy   string  `json:"lastUpdateBy"`   // 更新人
	LastUpdateTime string  `json:"lastUpdateTime"` // 更新时间
	DelFlag        int64   `json:"delFlag"`        // 是否删除  0：已删除  1：正常
}

type ListDeptResp struct {
	Code    string          `json:"code"`
	Message string          `json:"message"`
	Data    []*ListDeptData `json:"data"`
	Success bool            `json:"success"`
	Total   int64           `json:"total"`
}

type UpdateDeptReq struct {
	Id        int64   `json:"id"`                // 编号
	Name      string  `json:"name"`              // 机构名称
	ParentId  int64   `json:"parentId"`          // 上级机构ID，一级机构为0
	ParentIds []int64 `json:"parentIds"`         // 上级机构ID
	OrderNum  int64   `json:"orderNum"`          // 排序
	DelFlag   int64   `json:"delFlag,default=2"` // 是否删除  0：已删除  1：正常
}

type UpdateDeptResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type DeleteDeptReq struct {
	Ids []int64 `json:"ids"`
}

type DeleteDeptResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type ListLoginLogReq struct {
	Current  int64  `json:"current,default=1"`
	PageSize int64  `json:"pageSize,default=20"`
	UserName string `json:"userName,optional"`
	Ip       string `json:"ip,optional"` // IP地址
}

type ListLoginLogData struct {
	Id             int64  `json:"id"`             // 编号
	UserName       string `json:"userName"`       // 用户名
	Status         string `json:"status"`         // 登录状态（online:在线，登录初始状态，方便统计在线人数；login:退出登录后将online置为login；logout:退出登录）
	Ip             string `json:"ip"`             // IP地址
	CreateBy       string `json:"createBy"`       // 创建人
	CreateTime     string `json:"createTime"`     // 创建时间
	LastUpdateBy   string `json:"lastUpdateBy"`   // 更新人
	LastUpdateTime string `json:"lastUpdateTime"` // 更新时间
}

type ListLoginLogResp struct {
	Code     string              `json:"code"`
	Message  string              `json:"message"`
	Current  int64               `json:"current,default=1"`
	Data     []*ListLoginLogData `json:"data"`
	PageSize int64               `json:"pageSize,default=20"`
	Success  bool                `json:"success"`
	Total    int64               `json:"total"`
}

type DeleteLoginLogReq struct {
	Ids []int64 `json:"ids"`
}

type DeleteLoginLogResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type ListSysLogReq struct {
	Current  int64  `json:"current,default=1"`
	PageSize int64  `json:"pageSize,default=20"`
	UserName string `json:"userName,optional"` // 用户名
	Method   string `json:"method,optional"`   // 请求方法
}

type ListSysLogData struct {
	Id             int64  `json:"id"`             // 编号
	UserName       string `json:"userName"`       // 用户名
	Operation      string `json:"operation"`      // 用户操作
	Method         string `json:"method"`         // 请求方法
	RequestParams  string `json:"requestParams"`  // 请求参数
	ResponseParams string `json:"responseParams"` // 响应参数
	Time           int64  `json:"time"`           // 执行时长(毫秒)
	Ip             string `json:"ip"`             // IP地址
	OperationTime  string `json:"operationTime"`  // 操作时间
}

type ListSysLogResp struct {
	Code     string            `json:"code"`
	Message  string            `json:"message"`
	Current  int64             `json:"current,default=1"`
	Data     []*ListSysLogData `json:"data"`
	PageSize int64             `json:"pageSize,default=20"`
	Success  bool              `json:"success"`
	Total    int64             `json:"total"`
}

type DeleteSysLogReq struct {
	Ids []int64 `json:"ids"`
}

type DeleteSysLogResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type AddConfigReq struct {
	Value       string `json:"value"`       // 数据值
	Label       string `json:"label"`       // 标签名
	Type        string `json:"type"`        // 类型
	Description string `json:"description"` // 描述
	Sort        int64  `json:"sort"`        // 排序（升序）
	Remarks     string `json:"remarks"`     // 备注信息
}

type AddConfigResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type ListConfigReq struct {
	Current  int64 `json:"current,default=1"`
	PageSize int64 `json:"pageSize,default=20"`
}

type ListConfigData struct {
	Id             int64  `json:"id"`             // 编号
	Value          string `json:"value"`          // 数据值
	Label          string `json:"label"`          // 标签名
	Type           string `json:"type"`           // 类型
	Description    string `json:"description"`    // 描述
	Sort           int64  `json:"sort"`           // 排序（升序）
	CreateBy       string `json:"createBy"`       // 创建人
	CreateTime     string `json:"createTime"`     // 创建时间
	LastUpdateBy   string `json:"lastUpdateBy"`   // 更新人
	LastUpdateTime string `json:"lastUpdateTime"` // 更新时间
	Remarks        string `json:"remarks"`        // 备注信息
	DelFlag        int64  `json:"delFlag"`        // 是否删除  0：已删除  1：正常
}

type ListConfigResp struct {
	Code     string            `json:"code"`
	Message  string            `json:"message"`
	Current  int64             `json:"current,default=1"`
	Data     []*ListConfigData `json:"data"`
	PageSize int64             `json:"pageSize,default=20"`
	Success  bool              `json:"success"`
	Total    int64             `json:"total"`
}

type UpdateConfigReq struct {
	Id          int64  `json:"id"`          // 编号
	Value       string `json:"value"`       // 数据值
	Label       string `json:"label"`       // 标签名
	Type        string `json:"type"`        // 类型
	Description string `json:"description"` // 描述
	Sort        int64  `json:"sort"`        // 排序（升序）
	Remarks     string `json:"remarks"`     // 备注信息
}

type UpdateConfigResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type DeleteConfigReq struct {
	Ids []int64 `json:"ids"`
}

type DeleteConfigResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type AddJobReq struct {
	JobName  string `json:"jobName"`  // 职位名称
	Remarks  string `json:"remarks"`  // 备注
	OrderNum int64  `json:"orderNum"` // 排序
	DelFlag  int64  `json:"delFlag"`  // 是否删除  0：已删除  1：正常
}

type AddJobResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type ListJobReq struct {
	Current  int64  `json:"current,default=1"`
	PageSize int64  `json:"pageSize,default=20"`
	JobName  string `json:"jobName,optional"`
	DelFlag  int64  `json:"delFlag,default=2"` // 是否删除  0：已删除  1：正常
}

type ListJobData struct {
	Id             int64  `json:"id"`             // 编号
	JobName        string `json:"jobName"`        // 职位名称
	OrderNum       int64  `json:"orderNum"`       // 排序
	CreateBy       string `json:"createBy"`       // 创建人
	CreateTime     string `json:"createTime"`     // 创建时间
	LastUpdateBy   string `json:"lastUpdateBy"`   // 更新人
	LastUpdateTime string `json:"lastUpdateTime"` // 更新时间
	DelFlag        int64  `json:"delFlag"`        // 是否删除  0：已删除  1：正常
	Remarks        string `json:"remarks"`        // 备注
}

type ListJobResp struct {
	Code     string         `json:"code"`
	Message  string         `json:"message"`
	Current  int64          `json:"current,default=1"`
	Data     []*ListJobData `json:"data"`
	PageSize int64          `json:"pageSize,default=20"`
	Success  bool           `json:"success"`
	Total    int64          `json:"total"`
}

type UpdateJobReq struct {
	Id       int64  `json:"id"`       // 编号
	JobName  string `json:"jobName"`  // 职位名称
	OrderNum int64  `json:"orderNum"` // 排序
	Remarks  string `json:"remarks"`  // 备注
	DelFlag  int64  `json:"delFlag"`  // 是否删除  0：已删除  1：正常
}

type UpdateJobResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type DeleteJobReq struct {
	Ids []int64 `json:"ids"`
}

type DeleteJobResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type UploadResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
	Data    string `json:"data"`
}

type AddUavHistoryReq struct {
	UavId      int64  `json:"uav_id"`      //无人机id
	UavName    string `json:"uav_name"`    // 巡检无人机名字
	FlyID      int64  `json:"fly_id"`      // 巡检路线id
	FlyName    string `json:"fly_name"`    // 巡检路线名字
	Operator   string `json:"operator"`    //操作者
	CreateTime string `json:"create_time"` //创建时间
	EndTime    string `json:"end_time"`    //结束时间
}

type AddUavHistoryResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type ListUavHistoryReq struct {
	Current    int64  `json:"current,default=1"`
	PageSize   int64  `json:"pageSize,default=20"`
	HistoryID  int64  `json:"history_id,default=-1"` //无人机id
	CreateTime string `json:"create_time"`           //创建时间
	Status     int64  `json:"status,default=-1"`     //无人机id
}

type ListtUavHistoryData struct {
	Id         int64  `json:"id"`
	UavId      int64  `json:"uav_id"`      //无人机id
	UavName    string `json:"uav_name"`    // 巡检无人机名字
	FlyID      int64  `json:"fly_id"`      // 巡检路线id
	FlyName    string `json:"fly_name"`    // 巡检路线名字
	Operator   string `json:"operator"`    //操作者
	Status     int64  `json:"status"`      // -1,异常结束，0->起飞；1->正常完成
	Remark     string `json:"remark"`      // 异常结束原因
	CreateTime string `json:"create_time"` //创建时间
	EndTime    string `json:"end_time"`    //结束时间
}

type ListUavHistoryResp struct {
	Current  int64                  `json:"current,default=1"`
	Data     []*ListtUavHistoryData `json:"data"`
	PageSize int64                  `json:"pageSize,default=20"`
	Success  bool                   `json:"success"`
	Total    int64                  `json:"total"`
	Code     string                 `json:"code"`
	Message  string                 `json:"message"`
}

type AddPeopleReq struct {
	Level    int64  `json:"level"`    // 人员等级 本部,0，外来 1，工程 1
	Username string `json:"username"` // 用户名
	Phone    string `json:"phone"`    // 手机号码
	Status   int64  `json:"status"`   // 帐号启用状态:0->禁用；1->启用
	Icon     string `json:"icon"`     // 头像
	Gender   int64  `json:"gender"`   // 性别：0->未知；1->男；2->女
}

type AddPeopleResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type ListPeopleReq struct {
	Current  int64  `json:"current,default=1"`
	PageSize int64  `json:"pageSize,default=20"`
	Username string `json:"username,optional"` // 用户名
	Phone    string `json:"phone,optional"`    // 手机号码
	Status   int64  `json:"status,default=2"`  // 帐号启用状态:0->禁用；1->启用
}

type ListtPeopleData struct {
	Id         int64  `json:"id"`
	Level      int64  `json:"level"`       // 人员等级 本部，外来，工程
	Username   string `json:"username"`    // 用户名
	Phone      string `json:"phone"`       // 手机号码
	Status     int64  `json:"status"`      // 帐号启用状态:0->禁用；1->启用
	Icon       string `json:"icon"`        // 头像
	Gender     int64  `json:"gender"`      // 性别：0->未知；1->男；2->女
	CreateTime string `json:"create_time"` // 注册时间
}

type ListPeopleResp struct {
	Code     string             `json:"code"`
	Message  string             `json:"message"`
	Current  int64              `json:"current,default=1"`
	Data     []*ListtPeopleData `json:"data"`
	PageSize int64              `json:"pageSize,default=20"`
	Success  bool               `json:"success"`
	Total    int64              `json:"total"`
}

type UpdatePeopleReq struct {
	Id         int64  `json:"id"`
	Level      int64  `json:"level"`       // 人员等级 本部，外来，工程
	Username   string `json:"username"`    // 用户名
	Phone      string `json:"phone"`       // 手机号码
	Status     int64  `json:"status"`      // 帐号启用状态:0->禁用；1->启用
	Icon       string `json:"icon"`        // 头像
	Gender     int64  `json:"gender"`      // 性别：0->未知；1->男；2->女
	Birthday   string `json:"birthday"`    // 生日
	CreateTime string `json:"create_time"` // 注册时间
}

type UpdatePeopleResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type DeletePeopleReq struct {
	Ids []int64 `json:"ids"`
}

type DeletePeopleResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type AddUavPlanReq struct {
	Uav_id  int64  `json:"uav_id"`            // 无人机ID
	UAVName string `json:"uav_name,optional"` //飞机时间
	Name    string `json:"name,optional"`     //飞行计划名字
	Plan    string `json:"plan"`              //飞行计划时间
	Fly_id  int64  `json:"fly_id"`            //巡检路线id
	FlyName string `json:"fly_name,optional"` //巡检路线id
	Status  int64  `json:"status,optional"`   //状态
}

type AddUavPlanResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type ListUavPlanReq struct {
	Current  int64  `json:"current,default=1"`
	PageSize int64  `json:"pageSize,default=20"`
	Uav_name string `json:"uav_name,optional"`  // 无人机ID
	Fly_name string `json:"fly_namem,optional"` //巡检路线id
}

type ListtUavPlanData struct {
	Id      int64  `json:"id"`
	Uav_id  int64  `json:"uav_id"`   // 无人机ID
	Name    string `json:"name"`     //飞行计划时间
	UAVName string `json:"uav_name"` //飞行计划时间
	Plan    string `json:"plan"`     //飞行计划时间
	Fly_id  int64  `json:"fly_id"`   //巡检路线id
	FlyName string `json:"fly_name"` //巡检路线id
	Status  int64  `json:"status"`   //状态
}

type ListUavPlanResp struct {
	Code     string              `json:"code"`
	Message  string              `json:"message"`
	Current  int64               `json:"current,default=1"`
	Data     []*ListtUavPlanData `json:"data"`
	PageSize int64               `json:"pageSize,default=20"`
	Success  bool                `json:"success"`
	Total    int64               `json:"total"`
}

type UpdateUavPlanReq struct {
	Id      int64  `json:"id"`
	Uav_id  int64  `json:"uav_id"`   // 无人机ID
	Plan    string `json:"plan"`     //飞行计划时间
	Fly_id  int64  `json:"fly_id"`   //巡检路线id
	Name    string `json:"name"`     //飞行计划时间
	UAVName string `json:"uav_name"` //飞行计划时间
	FlyName string `json:"fly_name"` //巡检路线Name
}

type UpdateUavPlanResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type DeleteUavPlanReq struct {
	Ids []int64 `json:"ids"`
}

type DeleteUavPlanResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type AddUavDeviceReq struct {
	Name         string `json:"name"`
	Ip           string `json:"ip"`
	Port         int64  `json:"port"`
	R_Port       int64  `json:"r_port"`
	Hangar_ip    string `json:"hangar_ip"`
	Hangar_port  int64  `json:"hangar_port"`
	Hangar_rport int64  `json:"hangar_rport"`
	Cam_ip       string `json:"cam_ip"`
	Cam_port     int64  `json:"cam_port"`
	Cam_url      string `json:"cam_url"`
	UavZubo      int64  `json:"uav_zubo"`
	Network      string `json:"network"`
	Joystick     string `json:"joystick"`
	Status       int64  `json:"status"`
}

type AddUavDeviceResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type ListUavDeviceReq struct {
	Current  int64 `json:"current,default=1"`
	PageSize int64 `json:"pageSize,default=20"`
	Id       int64 `json:"id,optional"`
	Status   int64 `json:"status,optional"`
	UavZubo  int64 `json:"uav_zubo,optional"`
}

type ListUavDeviceData struct {
	Id           int64  `json:"id"`
	Name         string `json:"name"`
	Ip           string `json:"ip"`
	Port         int64  `json:"port"`
	R_Port       int64  `json:"r_port"`
	Hangar_ip    string `json:"hangar_ip"`
	Hangar_port  int64  `json:"hangar_port"`
	Hangar_rport int64  `json:"hangar_rport"`
	Cam_ip       string `json:"cam_ip"`
	Cam_port     int64  `json:"cam_port"`
	Cam_url      string `json:"cam_url"`
	UavZubo      int64  `json:"uav_zubo"`
	Joystick     string `json:"joystick"`
	Network      string `json:"network"`
	Status       int64  `json:"status"`
}

type ListUavDeviceResp struct {
	Code     string               `json:"code"`
	Message  string               `json:"message"`
	Current  int64                `json:"current,default=1"`
	Data     []*ListUavDeviceData `json:"data"`
	PageSize int64                `json:"pageSize,default=20"`
	Success  bool                 `json:"success"`
	Total    int64                `json:"total"`
}

type UpdateUavDeviceReq struct {
	Id           int64  `json:"id"`
	Name         string `json:"name"`
	Ip           string `json:"ip"`
	Port         int64  `json:"port"`
	R_Port       int64  `json:"r_port"`
	Hangar_ip    string `json:"hangar_ip"`
	Hangar_port  int64  `json:"hangar_port"`
	Hangar_rport int64  `json:"hangar_rport"`
	Cam_ip       string `json:"cam_ip"`
	Cam_port     int64  `json:"cam_port"`
	Cam_url      string `json:"cam_url"`
	UavZubo      int64  `json:"uav_zubo"`
	Joystick     string `json:"joystick"`
	Network      string `json:"network"`
	Status       int64  `json:"status"`
}

type UpdateUavDeviceResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type DeleteUavDeviceReq struct {
	Ids []int64 `json:"ids"`
}

type DeleteUavDeviceResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type AddUavFlyReq struct {
	Name    string `json:"name"`    // 路线名称
	Data    string `json:"data"`    //路线实惠
	Creator string `json:"creator"` // 创建者
}

type AddUavFlyResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type ListUavFlyReq struct {
	Current  int64 `json:"current,default=1"`
	PageSize int64 `json:"pageSize,default=20"`
	Id       int64 `json:"id,optional"`
}

type ListUavFlyData struct {
	Id         int64  `json:"id"`
	Name       string `json:"name"`        // 路线名称
	Data       string `json:"data"`        //路线实惠
	CreateTime string `json:"create_time"` // 创建时间
	Creator    string `json:"creator"`     // 创建者
}

type ListUavFlyResp struct {
	Current  int64             `json:"current,default=1"`
	Data     []*ListUavFlyData `json:"data"`
	PageSize int64             `json:"pageSize,default=20"`
	Success  bool              `json:"success"`
	Total    int64             `json:"total"`
	Code     string            `json:"code"`
	Message  string            `json:"message"`
}

type UpdateUavFlyReq struct {
	Id         int64  `json:"id"`
	Name       string `json:"name"`        // 路线名称
	Data       string `json:"data"`        //路线实惠
	CreateTime string `json:"create_time"` // 创建时间
	Creator    string `json:"creator"`     // 创建者
}

type UpdateUavFlyResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type DeleteUavFlyReq struct {
	Ids []int64 `json:"ids"`
}

type DeleteUavFlyResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type AddUavNetworkReq struct {
	Name string `json:"name"` //频段名称
	Band int64  `json:"band"` //频段号
	Type int64  `json:"type"` //频段类型
}

type AddUavNetworkResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type ListUavNetworkReq struct {
	Current  int64 `json:"current,default=1"`
	PageSize int64 `json:"pageSize,default=20"`
}

type ListtUavNetworkData struct {
	Id   int64  `json:"id"`
	Name string `json:"name"` //频段名称
	Band int64  `json:"band"` //频段号
	Type int64  `json:"type"` //频段类型
}

type ListUavNetworkResp struct {
	Code     string                 `json:"code"`
	Message  string                 `json:"message"`
	Current  int64                  `json:"current,default=1"`
	Data     []*ListtUavNetworkData `json:"data"`
	PageSize int64                  `json:"pageSize,default=20"`
	Success  bool                   `json:"success"`
	Total    int64                  `json:"total"`
}

type UpdateUavNetworkReq struct {
	Id   int64  `json:"id"`
	Name string `json:"name"` //频段名称
	Band int64  `json:"band"` //频段号
	Type int64  `json:"type"` //频段类型
}

type UpdateUavNetworkResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type DeleteUavNetworkReq struct {
	Ids []int64 `json:"ids"`
}

type DeleteUavNetworkResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type ListAlertHistoryReq struct {
	Current   int64  `json:"current,default=1"`
	PageSize  int64  `json:"pageSize,default=20"`
	Type      int64  `json:"type,optional"` //'消息类型:0-全部 1-巡检路线 2-入侵 3-烟火 4-人员 5-车辆',
	Starttime string `json:"start_time,optional"`
	Endtime   string `json:"end_time,optional"`   //??时间不是一个时间段么？
	Platform  int64  `json:"platform,optional"`   //监控的平台 '使用平台：0-全部 1-飞机 2-摄像头;3-机库;4-AI',
	HistoryID int64  `json:"history_id,optional"` // 巡检路线id 告警信息和巡检路线id绑定 巡检路线->告警路线 一对多
	Confirm   int64  `json:"confirm,optional"`    //是否是 审查过的。
}

type ListAlertHistoryData struct {
	Id        int64   `json:"id"`
	Name      string  `json:"name"`  //报警内容
	Image     string  `json:"image"` //报警图片
	Type      int64   `json:"type"`  //报警类型
	Code      string  `json:"code"`
	Level     int64   `json:"level"`
	Count     int64   `json:"count"`
	Platform  int64   `json:"platform"` //监控的平台 '使用平台：0-全部 1-飞机 2-摄像头;3-机库;4-AI',
	Starttime string  `json:"start_time"`
	Note      string  `json:"note"`
	Lat       float64 `json:"lat"`
	Lon       float64 `json:"lon"`
	Alt       float64 `json:"alt"`
	HistoryID int64   `json:"history_id"` // 巡检路线id 告警信息和巡检路线id绑定 巡检路线->告警路线 一对多
	Confirm   int64   `json:"confirm"`    //是否审查过的
}

type ListAlertHistoryResp struct {
	Current  int64                   `json:"current,default=1"`
	Data     []*ListAlertHistoryData `json:"data"`
	PageSize int64                   `json:"pageSize,default=20"`
	Success  bool                    `json:"success"`
	Total    int64                   `json:"total"`
	Code     string                  `json:"code"`
	Message  string                  `json:"message"`
}

type ListAlertData struct {
	Id   int64   `json:"id"`
	Type int64   `json:"type"`
	Lat  float64 `json:"lat"`
	Lon  float64 `json:"lon"`
	Alt  float64 `json:"alt"`
}

type Datayesterday struct {
	TodayData []int64 `json:"todaydata"`
	YestData  []int64 `json:"ydataToday"`
}

type ListAlertStatisticsResp struct {
	Data             []*ListAlertData `json:"data"`
	WeekCount        []int64          `json:"week_data"`
	TodayYesterday   *Datayesterday   `json:"today_yesterday"`
	AlertTotals      []int64          `json:"alert_total"`
	AlertConfirms    []int64          `json:"alert_confirms"`
	AlertNotConfirms []int64          `json:"alert_not_confirms"`
	Total            int64            `json:"total"`
	Completion       int64            `json:"completion"`
	TotalTime        int64            `json:"totaltime"`
}

type UpdateAlertHistoryReq struct {
	Id int64 `json:"id,default=1"`
}

type UpdateAlertHistoryResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type ConfirmAlertHistoryReq struct {
	Id      int64 `json:"id"`
	Confirm int64 `json:"confirm"` //0 未确认 1  已经检查
}

type ConfirmAlertHistoryResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type AddCamerasReq struct {
	Name      string  `json:"name"`
	Ip        string  `json:"ip"`
	Platform  int64   `json:"platform"`
	Tunnel    int64   `json:"tunnel"`
	Url       string  `json:"url"`
	Lat       float64 `json:"lat"`
	Lon       float64 `json:"lon"`
	Alt       float64 `json:"alt"`
	Status    int64   `json:"status"`
	Ai_status int64   `json:"ai_status"`
}

type AddCamerasResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type ListCamerasReq struct {
	Current  int64 `json:"current,default=1"`
	PageSize int64 `json:"pageSize,default=20"`
}

type ListCamerasData struct {
	Id        int64   `json:"id"`
	Name      string  `json:"name"`
	Ip        string  `json:"ip"`
	Platform  int64   `json:"platform"`
	Tunnel    int64   `json:"tunnel"`
	Url       string  `json:"url"`
	Lat       float64 `json:"lat"`
	Lon       float64 `json:"lon"`
	Alt       float64 `json:"alt"`
	Status    int64   `json:"status"`
	Ai_status int64   `json:"ai_status"`
}

type ListCamerasResp struct {
	Code     string             `json:"code"`
	Message  string             `json:"message"`
	Current  int64              `json:"current,default=1"`
	Data     []*ListCamerasData `json:"data"`
	PageSize int64              `json:"pageSize,default=20"`
	Success  bool               `json:"success"`
	Total    int64              `json:"total"`
}

type UpdateCamerasReq struct {
	Id        int64   `json:"id"`
	Name      string  `json:"name"`
	Ip        string  `json:"ip"`
	Platform  int64   `json:"platform"`
	Tunnel    int64   `json:"tunnel"`
	Url       string  `json:"url"`
	Lat       float64 `json:"lat"`
	Lon       float64 `json:"lon"`
	Alt       float64 `json:"alt"`
	Status    int64   `json:"status"`
	Ai_status int64   `json:"ai_status"`
}

type UpdateCamerasResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type DeleteCamerasReq struct {
	Ids []int64 `json:"ids"`
}

type DeleteCamerasResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type AddCarsReq struct {
	Name   string `json:"name"`   // '人名称'
	Card   string `json:"card"`   //'车牌号',
	Photo  string `json:"photo"`  //'车辆照片',
	Type   int64  `json:"type"`   //'消息类型:0-全部 1-巡检路线 2-入侵 3-烟火 4-人员 5-车辆',
	Phone  string `json:"phone"`  //'手机号码',
	Agency string `json:"agency"` //  所属机构名称',
	Status int64  `json:"status"` //帐号启用状态:0->禁用；1->启用
}

type AddCarsResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type ListCarsReq struct {
	Current  int64 `json:"current,default=1"`
	PageSize int64 `json:"pageSize,default=20"`
}

type ListCarsData struct {
	Id     int64  `json:"id"`
	Name   string `json:"name"`   // '人名称'
	Card   string `json:"card"`   //'车牌号',
	Photo  string `json:"photo"`  //'车辆照片',
	Type   int64  `json:"type"`   //'消息类型:0-全部 1-巡检路线 2-入侵 3-烟火 4-人员 5-车辆',
	Phone  string `json:"phone"`  //'手机号码',
	Agency string `json:"agency"` //  所属机构名称',
	Status int64  `json:"status"` //帐号启用状态:0->禁用；1->启用
}

type ListCarsResp struct {
	Code     string          `json:"code"`
	Message  string          `json:"message"`
	Current  int64           `json:"current,default=1"`
	Data     []*ListCarsData `json:"data"`
	PageSize int64           `json:"pageSize,default=20"`
	Success  bool            `json:"success"`
	Total    int64           `json:"total"`
}

type UpdateCarsReq struct {
	Id     int64  `json:"id"`
	Name   string `json:"name"`   // '人名称'
	Card   string `json:"card"`   //'车牌号',
	Photo  string `json:"photo"`  //'车辆照片',
	Type   int64  `json:"type"`   //'消息类型:0-全部 1-巡检路线 2-入侵 3-烟火 4-人员 5-车辆',
	Phone  string `json:"phone"`  //'手机号码',
	Agency string `json:"agency"` //  所属机构名称',
	Status int64  `json:"status"` //帐号启用状态:0->禁用；1->启用
}

type UpdateCarsResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type DeleteCarsReq struct {
	Ids []int64 `json:"ids"`
}

type DeleteCarsResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type ListUavStatisticsReq struct {
	Current  int64 `json:"current,default=1"`
	PageSize int64 `json:"pageSize,default=20"`
}

type ListtUavStatisticsData struct {
	Id         int64  `json:"id"`
	Total      int64  `json:"total"`       // 总报警数
	Person     int64  `json:"person"`      // 人报警数
	Car        int64  `json:"car"`         // 车报警数
	Bicycle    int64  `json:"bicycle"`     // 自行车报警数
	Bus        int64  `json:"bus"`         // 汽车报警数
	Truck      int64  `json:"truck"`       // 卡车报警数
	BoxTruck   int64  `json:"box_truck"`   // 厢式货车报警数
	Tricycle   int64  `json:"tricycle"`    // 三轮车报警数
	Motorcycle int64  `json:"motorcycle"`  // 摩托车报警数
	Smoke      int64  `json:"smoke"`       // 烟雾报警数
	Fire       int64  `json:"fire"`        // 火警报警数
	Remark     string `json:"remark"`      // 备注
	Snapshots  string `json:"snapshots"`   // 报警图片列表
	Day        string `json:"create_time"` //创建时间
}

type ListUavStatisticsResp struct {
	Code     string                    `json:"code"`
	Message  string                    `json:"message"`
	Current  int64                     `json:"current,default=1"`
	Data     []*ListtUavStatisticsData `json:"data"`
	PageSize int64                     `json:"pageSize,default=20"`
	Success  bool                      `json:"success"`
	Total    int64                     `json:"total"`
}

type DeleteUavStatisticsReq struct {
	Ids []int64 `json:"ids"`
}

type DeleteUavStatisticsResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}
