// Code generated by goctl. DO NOT EDIT.

package uavmodel

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	uavPeopleFieldNames          = builder.RawFieldNames(&UavPeople{})
	uavPeopleRows                = strings.Join(uavPeopleFieldNames, ",")
	uavPeopleRowsExpectAutoSet   = strings.Join(stringx.Remove(uavPeopleFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	uavPeopleRowsWithPlaceHolder = strings.Join(stringx.Remove(uavPeopleFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	uavPeopleModel interface {
		Insert(ctx context.Context, data *UavPeople) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*UavPeople, error)
		Update(ctx context.Context, data *UavPeople) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUavPeopleModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UavPeople struct {
		Id         int64     `db:"id"`          // 编号
		Username   string    `db:"username"`    // 人名称
		Icon       string    `db:"icon"`        // 人头像
		Level      int64     `db:"level"`       // 等级分类 人员等级 本部,0，外来 1，工程 1
		Phone      string    `db:"phone"`       // 手机号码
		Status     int64     `db:"status"`      //  帐号启用状态:0->禁用；1->启用
		Gender     int64     `db:"gender"`      //   性别：0->未知；1->男；2->女
		CreateTime time.Time `db:"create_time"` // 飞行开始时间
	}
)

func newUavPeopleModel(conn sqlx.SqlConn) *defaultUavPeopleModel {
	return &defaultUavPeopleModel{
		conn:  conn,
		table: "`uav_people`",
	}
}

func (m *defaultUavPeopleModel) withSession(session sqlx.Session) *defaultUavPeopleModel {
	return &defaultUavPeopleModel{
		conn:  sqlx.NewSqlConnFromSession(session),
		table: "`uav_people`",
	}
}

func (m *defaultUavPeopleModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUavPeopleModel) FindOne(ctx context.Context, id int64) (*UavPeople, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", uavPeopleRows, m.table)
	var resp UavPeople
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUavPeopleModel) Insert(ctx context.Context, data *UavPeople) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, uavPeopleRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Username, data.Icon, data.Level, data.Phone, data.Status, data.Gender)
	return ret, err
}

func (m *defaultUavPeopleModel) Update(ctx context.Context, data *UavPeople) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, uavPeopleRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Username, data.Icon, data.Level, data.Phone, data.Status, data.Gender, data.Id)
	return err
}

func (m *defaultUavPeopleModel) tableName() string {
	return m.table
}
