// Code generated by goctl. DO NOT EDIT.
// Source: uav.proto

package server

import (
	"context"

	"zero-admin/rpc/uav/internal/logic/uavpeopleservice"
	"zero-admin/rpc/uav/internal/svc"
	"zero-admin/rpc/uav/uavlient"
)

type UavPeopleServiceServer struct {
	svcCtx *svc.ServiceContext
	uavlient.UnimplementedUavPeopleServiceServer
}

func NewUavPeopleServiceServer(svcCtx *svc.ServiceContext) *UavPeopleServiceServer {
	return &UavPeopleServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *UavPeopleServiceServer) UavPeopleAdd(ctx context.Context, in *uavlient.AddUavPeopleReq) (*uavlient.UavPeopleAddResp, error) {
	l := uavpeopleservicelogic.NewUavPeopleAddLogic(ctx, s.svcCtx)
	return l.UavPeopleAdd(in)
}

func (s *UavPeopleServiceServer) UavPeopleList(ctx context.Context, in *uavlient.ListUavPeopleReq) (*uavlient.ListUavPeopleResp, error) {
	l := uavpeopleservicelogic.NewUavPeopleListLogic(ctx, s.svcCtx)
	return l.UavPeopleList(in)
}

func (s *UavPeopleServiceServer) UavPeopleUpdate(ctx context.Context, in *uavlient.UpdateUavPeopleReq) (*uavlient.UpdateUavPeopleResp, error) {
	l := uavpeopleservicelogic.NewUavPeopleUpdateLogic(ctx, s.svcCtx)
	return l.UavPeopleUpdate(in)
}

func (s *UavPeopleServiceServer) UavPeopleFindById(ctx context.Context, in *uavlient.UavPeopleFindByIdReq) (*uavlient.ListUavPeopleResp, error) {
	l := uavpeopleservicelogic.NewUavPeopleFindByIdLogic(ctx, s.svcCtx)
	return l.UavPeopleFindById(in)
}
